### ISSUE TITLE
load csv with date field

### ISSUE THREAD

**Issue by graziella79** [datastax/dsbulk#385]
I need to upload a csv file which contains a date field in yyyyMMddHHmmss format: example(20210515031117).
The field will be mapped to a cassandra table with timestamp type.
I ran the dsbulk command adding the option --codec.date 'yyyyMMddHHmmss' but it doesn't work

This is the error:
com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException: Could not map field call_date to variable call_date; conversion from Java type java.lang.String to CQL type TIMESTAMP failed for raw value: 20210515031117.
        at com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException.encodeFailed(InvalidMappingException.java:96)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.bindColumn(DefaultRecordMapper.java:164)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.map(DefaultRecordMapper.java:133)
        at java.lang.Thread.run(Thread.java:748) [19 skipped]
Caused by: java.time.format.DateTimeParseException: Text '20210515031117' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1819)
        at com.datastax.oss.dsbulk.codecs.api.format.temporal.SimpleTemporalFormat.parse(SimpleTemporalFormat.java:48)
        at com.datastax.oss.dsbulk.codecs.api.format.temporal.ZonedTemporalFormat.parse(ZonedTemporalFormat.java:52)
        at com.datastax.oss.dsbulk.codecs.text.string.StringToTemporalCodec.parseTemporalAccessor(StringToTemporalCodec.java:46)
        at com.datastax.oss.dsbulk.codecs.text.string.StringToInstantCodec.externalToInternal(StringToInstantCodec.java:44)
        at com.datastax.oss.dsbulk.codecs.text.string.StringToInstantCodec.externalToInternal(StringToInstantCodec.java:27)
        at com.datastax.oss.dsbulk.codecs.api.ConvertingCodec.encode(ConvertingCodec.java:70)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.bindColumn(DefaultRecordMapper.java:162)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.map(DefaultRecordMapper.java:133)

what did i do wrong?
Thanks

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-4) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi the correct setting for timestamp type is `--codec.timestamp`.
