### ISSUE TITLE
Can't import empty string if it is part of partition key

### ISSUE THREAD

**Issue by makeable** [datastax/dsbulk#397]
I have some records that contain an empty value for certain columns on the partition key. This is perfectly valid as far as I am aware. Unfortunately, they cannot be loaded by dsbulk (from csv).

They raise the following error:

```
com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException: Primary key column X cannot be set to null. Check that your settings (schema.mapping or schema.query) match your dataset contents.
        at com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException.nullPrimaryKey(InvalidMappingException.java:64)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.bindColumn(DefaultRecordMapper.java:170)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.map(DefaultRecordMapper.java:133)
        at com.datastax.oss.dsbulk.connectors.csv.CSVConnector$CSVRecordReader.readNext(CSVConnector.java:293) [7 skipped]
        at java.lang.Thread.run(Thread.java:748) [20 skipped]
```

It seems that the csv connector treats empty non-quoted fields as nulls (even though the export itself was performed by dsbulk), so I force the csv connector to treat nulls as empty strings `--connector.csv.nullValue ""`, then I get the error:

```
com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException: Primary key column X cannot be set to empty. Check that your settings (schema.mapping or schema.query) match your dataset contents.
        at com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException.emptyPrimaryKey(InvalidMappingException.java:73)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.bindColumn(DefaultRecordMapper.java:171)
        at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.map(DefaultRecordMapper.java:133)
        at com.datastax.oss.dsbulk.connectors.csv.CSVConnector$CSVRecordReader.readNext(CSVConnector.java:293) [7 skipped]
        at java.lang.Thread.run(Thread.java:748) [20 skipped]
```

Looking at the code, it appears that if a field is part of partition key, then it can't be either empty or null:
https://github.com/datastax/dsbulk/blob/1.x/workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/schema/DefaultRecordMapper.java#L167

As far as I am aware, empty is valid, whereas null is not?

I am able to work around this, but thought it worth raising as an issue for clarification. If you can confirm this is unintentional behaviour I am happy to raise a patch accordingly.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-21) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi @makeable, empty strings are not allowed on partition key columns, however they are allowed on clustering columns and on regular columns:

```
cqlsh:test> create table test_empty(pk text, cc text, v text, primary key(pk, cc));
cqlsh:test> insert into test_empty (pk, cc, v) values ('foo', '', 'bar'); // OK
cqlsh:test> insert into test_empty (pk, cc, v) values ('foo', 'bar', ''); // OK
cqlsh:test> insert into test_empty (pk, cc, v) values ('', 'foo', 'bar'); // not OK
InvalidRequest: Error from server: code=2200 [Invalid query] message="Key may not be empty"
```

DSBulk will detect if a CSV field mapped to a partition key column is empty and will prevent that row from being loaded, since it is an invalid one. However, it should allow empty fields to be mapped to other column types.

If you think DSbulk is not behaving as expected, could you please provide a simple reproducer? This should include the table definition, a sample CSV file, and your DSBulk configuration.

Thanks!

**Comment by adutra** [comment]
Closing to avoid stale issues. Feel free to reopen if you have further questions. Thanks!

**Comment by makeable** [comment]
@adutra Sorry for delayed response. I ended up using a custom tool to import. Empty strings ARE allowed on partition key columns as part of a composite key.

**Comment by adutra** [comment]
Hi @makeable indeed there are cases where empty strings or blobs are accepted on partition key columns.

This was fixed by https://github.com/datastax/dsbulk/issues/411 and released in DSBulk 1.9.0.

If it's not too late, try it out and let us know if that fixes your problem. Thanks!

**Comment by makeable** [comment]
Thanks @adutra. Too late for this project, but ill check it out when i do some more generic loading.

**Comment by thoongnv** [comment]
I encountered the same issue on dsbulk 1.10.0. I have my data in this `targets.csz.gz`

```
hostname,domain,source,updated_at
www,aigportal.de,bounty-domains,2026-01-13
,nctools.com.au,top-sites,2026-01-13
,pinpointtesting.com,top-sites,2026-01-13
```

My table schema uses this `PRIMARY KEY (domain, hostname)` so `hostname` is kind of a clustering key here and not required to be null here (INSERT INTO worked fine). But `dsbulk load` causes errors.

```
Resource: file:/tmp/targets.csv.gz
Position: 21
Source: ,petalologia.com,top-sites,2026-01-13\u000a
com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException: Primary key column hostname cannot be set to null. Check that your settings (schema.mapping or schema.query) match your dataset contents.
	at com.datastax.oss.dsbulk.workflow.commons.schema.InvalidMappingException.nullPrimaryKey(InvalidMappingException.java:67)
	at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.bindColumn(DefaultRecordMapper.java:186)
	at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.bindStatement(DefaultRecordMapper.java:158)
	at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultRecordMapper.map(DefaultRecordMapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:829) [18 skipped]
```

**Comment by thoongnv** [comment]
Ah sorry, I missed this `--connector.csv.nullValue ""`. It worked fine now for me.
