### ISSUE TITLE
Exclude unsupported types from automatic timestamp and TTL preservation

### ISSUE THREAD

**Issue by adutra** [datastax/dsbulk#403]
Currently when unloading using the options `-timestamp` or `-ttl` (to automatically preserve cell timestamp and TTL) the operation will fail if the table being unloaded contains collections.

With OSS Cassandra, the operation fails right away because the generated query is invalid. The selector functions `writetime()` and `ttl()` cannot be applied to collections (even frozen ones, see [CASSANDRA-14533](https://issues.apache.org/jira/browse/CASSANDRA-14533)):

```
2022-02-16 14:27:36 ERROR Operation UNLOAD_TIMESTAMP_TTL failed: Cannot use selection function writeTime on collections.
com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Cannot use selection function writeTime on collections
	at com.datastax.oss.driver.api.core.servererrors.InvalidQueryException.copy(InvalidQueryException.java:48)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareSyncProcessor.process(CqlPrepareSyncProcessor.java:59)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareSyncProcessor.process(CqlPrepareSyncProcessor.java:31)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.prepare(SyncCqlSession.java:224)
	at com.datastax.oss.dsbulk.workflow.commons.settings.SchemaSettings.prepareStatementAndCreateMapping(SchemaSettings.java:720)
	at com.datastax.oss.dsbulk.workflow.commons.settings.SchemaSettings.createReadResultMapper(SchemaSettings.java:510)
	at com.datastax.oss.dsbulk.workflow.unload.UnloadWorkflow.init(UnloadWorkflow.java:150)
	at com.datastax.oss.dsbulk.runner.WorkflowThread.run(WorkflowThread.java:52)
```

With DSE, these functions are allowed to be applied to collections; but they return a list of BIGINTs (one element per collection item). The operation then fails during the row mapping phase with:

```
java.lang.IllegalArgumentException: Could not deserialize column "writetime(contact)" of type List(BIGINT, not frozen) as java.lang.String
	at com.datastax.oss.dsbulk.workflow.commons.schema.DefaultReadResultMapper.map(DefaultReadResultMapper.java:77)
	at java.lang.Thread.run(Thread.java:748) [17 skipped]
Caused by: java.lang.IllegalArgumentException: Cannot create a WriteTimeCodec for List(BIGINT, not frozen)
	at com.datastax.oss.dsbulk.mapping.DefaultMapping.createWritetimeCodec(DefaultMapping.java:101)
	at com.datastax.oss.dsbulk.mapping.DefaultMapping.lambda$codec$0(DefaultMapping.java:90)
```

We could improve this:

* If the server does not support unloading timestamp and TTL of collection columns (OSS C*):
  * Simply do not export it
  * Log a warning that timestamp and TTL data will not be preserved for these columns, and keep going.
* If the server supports it (DSE), then we should be able to export at least one value of the list. It's not possible to specify individual element timestamps and TTLs when loading anyways, so exporting one single value is the best we can do.
  * Modify `WriteTimeCodec` to also accept `list<bigint>`, and only retain the first element. 
  * For TTL variables we'll need to intercept them the same way we intercept writetime variables. Then, only retain the first element.
  * Log a warning explaining that some timestamps and TTLs may be lost.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-25) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Note that DataStax (private) project ZDM (Zero Downtime Migration) already excludes such columns. We may simply reuse some code from that project.

**Comment by adutra** [comment]
I have an implementation for this: #407 

However I gave up on the idea of intercepting lists of timestamps and TTLs on the fly. Not only it's extremely complex to implement, but it might not be desirable to use the same timestamp or TTL for all the elements in the collection.

Also note: it appears that it is also not possible to export timestamp and TTL for non-frozen UDTs. It's been taken care of in the PR mentioned above.
